[build]
  functions = './Server'
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  from = "/undefined"
  to = "/Shop"
  status = 200
  


[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"