[build]
  functions = './Server'
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/undefined"
  to = "/Shop"
  status = 200
  force = true # COMMENT: ensure that we always redirect

  


[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"